import { NextResponse } from 'next/server'

export async function GET() {
	// JSON stub for ESG reporting; PDF would be generated by a separate service
	return NextResponse.json({
		report: {
			title: 'Easy11 Sustainability Report (Dev)',
			period: '2025-Q4',
			kpis: {
				co2_total_kg: 412300,
				avg_per_order_kg: 1.98,
				recycled_pct: 31,
			},
			frameworks: ['GRI', 'SASB', 'CSRD'],
			notes: 'This is a development stub. Final reports include audited metrics and narratives.',
		},
	})
}


