name: 'easy11'
version: '1.0.0'

config-version: 2

profile: 'easy11'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  company_name: 'Easy11'

models:
  easy11:
    +materialized: table
    staging:
      +materialized: view
    marts:
      +materialized: table

seeds:
  easy11:
    +schema: raw

