easy11:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 4
      host: localhost
      port: 5432
      user: postgres
      password: postgres
      dbname: easy11_dev
      schema: analytics
    prod:
      type: postgres
      threads: 8
      host: {{ env_var('DB_HOST', 'prod-rds.amazonaws.com') }}
      port: 5432
      user: {{ env_var('DB_USER') }}
      password: {{ env_var('DB_PASSWORD') }}
      dbname: easy11_prod
      schema: analytics

