receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 5s
    send_batch_size: 1024

exporters:
  tempo:
    endpoint: http://tempo:4317
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
  kafka:
    brokers:
      - kafka:9092
    topic: events_ops_raw
  debug:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [tempo, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki, kafka]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]


